"""Render and optionally post sticky GitHub PR comments for scan results."""

from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from typing import Any

from terraguard.core.findings import ScanResult
from terraguard.exceptions import TerraGuardError

COMMENT_MARKER = "<!-- terraguard-scan-report -->"
MAX_FINDINGS = 25


def render(result: ScanResult, *, title: str = "TerraGuard Policy Scan") -> str:
    status = "FAILED" if result.failed else "PASSED"
    summary = result.to_dict()["summary"]
    lines = [
        COMMENT_MARKER,
        f"## {title}: {status}",
        "",
        "| Metric | Value |",
        "| --- | --- |",
        f"| Failed | `{str(result.failed).lower()}` |",
        f"| Fail on | `{result.fail_on}` |",
        f"| Findings | `{summary['total']}` |",
        f"| Critical | `{summary['critical']}` |",
        f"| High | `{summary['high']}` |",
        f"| Medium | `{summary['medium']}` |",
        f"| Suppressed | `{summary.get('suppressed', 0)}` |",
        "",
    ]

    if result.expired_suppressions:
        lines.extend(
            [
                "### Expired suppressions",
                "",
                "These exceptions have expired and are failing the gate:",
                "",
            ]
        )
        for item in result.expired_suppressions:
            lines.append(
                f"- `{item.get('policy_id')}`"
                + (f" on `{item.get('resource')}`" if item.get("resource") else "")
                + (f" (expired {item.get('expires')})" if item.get("expires") else "")
            )
        lines.append("")

    if not result.findings:
        lines.append("No policy violations found." if not result.failed else "No active findings.")
        lines.append("")
        lines.append("_Generated by TerraGuard CLI_")
        return "\n".join(lines)

    lines.extend(["### Findings", ""])
    for finding in result.findings[:MAX_FINDINGS]:
        controls = f" · controls: `{', '.join(finding.controls)}`" if finding.controls else ""
        lines.extend(
            [
                f"#### `{finding.severity.upper()}` {finding.policy_id} — {finding.title}",
                "",
                f"- Resource: `{finding.resource_address}` (`{finding.resource_type}`)",
                f"- {finding.message}{controls}",
                f"- Remediation: {finding.remediation}",
                "",
            ]
        )
        if finding.fix_hcl:
            lines.extend(["```hcl", finding.fix_hcl.rstrip(), "```", ""])

    remaining = len(result.findings) - MAX_FINDINGS
    if remaining > 0:
        lines.append(f"_…and {remaining} more finding(s). See the full JSON/SARIF artifacts._")
        lines.append("")

    if result.suppressed:
        lines.append(f"_Suppressed findings omitted from this comment: {len(result.suppressed)}_")
        lines.append("")

    lines.append("_Generated by TerraGuard CLI_")
    return "\n".join(lines)


def post_or_update_comment(
    body: str,
    *,
    repository: str | None = None,
    pr_number: int | None = None,
    token: str | None = None,
    api_url: str | None = None,
) -> dict[str, Any]:
    repository = repository or os.environ.get("GITHUB_REPOSITORY")
    token = token or os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    api_url = (api_url or os.environ.get("GITHUB_API_URL") or "https://api.github.com").rstrip("/")

    if pr_number is None:
        pr_number = _pr_number_from_env()

    if not repository or "/" not in repository:
        raise TerraGuardError("GITHUB_REPOSITORY is required to post a PR comment.")
    if not token:
        raise TerraGuardError("GITHUB_TOKEN (or GH_TOKEN) is required to post a PR comment.")
    if pr_number is None:
        raise TerraGuardError("Pull request number is required (pass --pr or set GITHUB_EVENT_PATH).")

    owner, repo = repository.split("/", 1)
    existing = _find_sticky_comment(api_url, owner, repo, pr_number, token)
    if existing is not None:
        return _request(
            "PATCH",
            f"{api_url}/repos/{owner}/{repo}/issues/comments/{existing['id']}",
            token,
            {"body": body},
        )
    return _request(
        "POST",
        f"{api_url}/repos/{owner}/{repo}/issues/{pr_number}/comments",
        token,
        {"body": body},
    )


def _pr_number_from_env() -> int | None:
    direct = os.environ.get("GITHUB_PR_NUMBER") or os.environ.get("PULL_REQUEST_NUMBER")
    if direct:
        return int(direct)

    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if not event_path:
        return None
    try:
        with open(event_path, encoding="utf-8") as handle:
            payload = json.loads(handle.read())
    except (OSError, json.JSONDecodeError):
        return None
    number = payload.get("number") or (payload.get("pull_request") or {}).get("number")
    return int(number) if number is not None else None


def _find_sticky_comment(
    api_url: str,
    owner: str,
    repo: str,
    pr_number: int,
    token: str,
) -> dict[str, Any] | None:
    page = 1
    while page <= 10:
        comments = _request(
            "GET",
            f"{api_url}/repos/{owner}/{repo}/issues/{pr_number}/comments?per_page=100&page={page}",
            token,
        )
        if not isinstance(comments, list) or not comments:
            return None
        for comment in comments:
            body = comment.get("body") or ""
            if COMMENT_MARKER in body:
                return comment
        if len(comments) < 100:
            return None
        page += 1
    return None


def _request(method: str, url: str, token: str, payload: dict[str, Any] | None = None) -> Any:
    data = None if payload is None else json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=data,
        method=method,
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "User-Agent": "terraguard-cli",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            raw = response.read().decode("utf-8")
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise TerraGuardError(f"GitHub API {method} failed ({exc.code}): {detail}") from exc
    except urllib.error.URLError as exc:
        raise TerraGuardError(f"GitHub API request failed: {exc}") from exc
